/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type Status = "PENDING" | "IN_PROGRESS" | "SUCCEEDED" | "FAILED";
export declare const Status: {
    readonly Pending: "PENDING";
    readonly InProgress: "IN_PROGRESS";
    readonly Succeeded: "SUCCEEDED";
    readonly Failed: "FAILED";
};
