/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CakeworkApi } from "../../../..";
import * as core from "../../../../core";

export const Parameters: core.serialization.Schema<
  serializers.Parameters.Raw,
  CakeworkApi.Parameters
> = core.serialization.record(
  core.serialization.string(),
  core.serialization.unknown()
);

export declare namespace Parameters {
  type Raw = Record<string, unknown>;
}
