/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CakeworkApi } from "../../../..";
import * as core from "../../../../core";

export const Project: core.serialization.Schema<
  serializers.Project.Raw,
  CakeworkApi.Project
> = core.serialization.string();

export declare namespace Project {
  type Raw = string;
}
