/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CakeworkApi } from "../../../..";
import * as core from "../../../../core";

export const RunResult: core.serialization.Schema<
  serializers.RunResult.Raw,
  CakeworkApi.RunResult
> = core.serialization.unknown();

export declare namespace RunResult {
  type Raw = unknown;
}
