/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CakeworkApi } from "../../../..";
import * as core from "../../../../core";

export const RunRequest: core.serialization.ObjectSchema<
  serializers.RunRequest.Raw,
  CakeworkApi.RunRequest
> = core.serialization.object({
  parameters: core.serialization
    .lazy(async () => (await import("../../..")).Parameters)
    .optional(),
  compute: core.serialization
    .lazyObject(async () => (await import("../../..")).Compute)
    .optional(),
});

export declare namespace RunRequest {
  interface Raw {
    parameters?: serializers.Parameters.Raw | null;
    compute?: serializers.Compute.Raw | null;
  }
}
