/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CakeworkApi } from "../../../..";
import * as core from "../../../../core";

export const Task: core.serialization.Schema<
  serializers.Task.Raw,
  CakeworkApi.Task
> = core.serialization.string();

export declare namespace Task {
  type Raw = string;
}
