/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class BadRequest extends Error {
  constructor() {
    super();
    Object.setPrototypeOf(this, BadRequest.prototype);
  }
}
