/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class InternalServerError extends Error {
  constructor() {
    super();
    Object.setPrototypeOf(this, InternalServerError.prototype);
  }
}
