/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class RunDoesNotExistError extends Error {
  constructor() {
    super();
    Object.setPrototypeOf(this, RunDoesNotExistError.prototype);
  }
}
