/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class UnauthorizedError extends Error {
  constructor() {
    super();
    Object.setPrototypeOf(this, UnauthorizedError.prototype);
  }
}
