# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cakework.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61kework.proto\x12\x08\x63\x61kework\"M\n\x07Request\x12\x12\n\nparameters\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\t\x12\x0f\n\x07project\x18\x03 \x01(\t\x12\r\n\x05runId\x18\x04 \x01(\t\"\x17\n\x05Reply\x12\x0e\n\x06result\x18\x01 \x01(\t27\n\x08\x43\x61kework\x12+\n\x03Run\x12\x11.cakework.Request\x1a\x0f.cakework.Reply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cakework_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=28
  _REQUEST._serialized_end=105
  _REPLY._serialized_start=107
  _REPLY._serialized_end=130
  _CAKEWORK._serialized_start=132
  _CAKEWORK._serialized_end=187
# @@protoc_insertion_point(module_scope)
