# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

# import cakework_pb2 as cakework__pb2
from cakework import cakework_pb2 as cakework__pb2

class CakeworkStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunActivity = channel.unary_unary(
                '/cakework.Cakework/RunActivity',
                request_serializer=cakework__pb2.Request.SerializeToString,
                response_deserializer=cakework__pb2.Reply.FromString,
                )


class CakeworkServicer(object):
    """The greeting service definition.
    """

    def RunActivity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CakeworkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.RunActivity,
                    request_deserializer=cakework__pb2.Request.FromString,
                    response_serializer=cakework__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cakework.Cakework', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Cakework(object):
    """The greeting service definition.
    """

    @staticmethod
    def RunActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cakework.Cakework/RunActivity',
            cakework__pb2.Request.SerializeToString,
            cakework__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
