# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cakework import frontend_pb2 as proto_dot_frontend__pb2


class FrontendStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallTask = channel.unary_unary(
                '/frontend.Frontend/CallTask',
                request_serializer=proto_dot_frontend__pb2.CallTaskRequest.SerializeToString,
                response_deserializer=proto_dot_frontend__pb2.CallTaskReply.FromString,
                )


class FrontendServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CallTask(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrontendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTask,
                    request_deserializer=proto_dot_frontend__pb2.CallTaskRequest.FromString,
                    response_serializer=proto_dot_frontend__pb2.CallTaskReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'frontend.Frontend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Frontend(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/frontend.Frontend/CallTask',
            proto_dot_frontend__pb2.CallTaskRequest.SerializeToString,
            proto_dot_frontend__pb2.CallTaskReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
