/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { CakeworkApi } from "../../../..";
import * as core from "../../../../core";
export declare const App: core.serialization.Schema<serializers.App.Raw, CakeworkApi.App>;
export declare namespace App {
    type Raw = string;
}
