/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { CakeworkApi } from "../../../..";
import * as core from "../../../../core";
export declare const Parameters: core.serialization.Schema<serializers.Parameters.Raw, CakeworkApi.Parameters>;
export declare namespace Parameters {
    type Raw = unknown[];
}
