/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { CakeworkApi } from "../../../..";
import * as core from "../../../../core";
export declare const RequestId: core.serialization.Schema<serializers.RequestId.Raw, CakeworkApi.RequestId>;
export declare namespace RequestId {
    type Raw = string;
}
