/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { CakeworkApi } from "../../../..";
import * as core from "../../../../core";
export declare const RunId: core.serialization.Schema<serializers.RunId.Raw, CakeworkApi.RunId>;
export declare namespace RunId {
    type Raw = string;
}
