/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { CakeworkApi } from "../../../..";
import * as core from "../../../../core";
export declare const Task: core.serialization.Schema<serializers.Task.Raw, CakeworkApi.Task>;
export declare namespace Task {
    type Raw = string;
}
