/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { CakeworkApi } from "../../../..";
import * as core from "../../../../core";
export declare const UserId: core.serialization.Schema<serializers.UserId.Raw, CakeworkApi.UserId>;
export declare namespace UserId {
    type Raw = string;
}
