# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cakeworkctl < Formula
  desc "CLI for cakework."
  homepage "https://github.com/usecakework/cakeworkctl"
  version "1.0.33"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/usecakework/cakeworkctl/releases/download/v1.0.33/cakeworkctl_1.0.33_Darwin_x86_64.tar.gz"
      sha256 "55d706e5ba99b1a0b15418bb42b0e90abdb0350bad21c5ea3db2453b21ea7088"

      def install
        bin.install "cakework"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/usecakework/cakeworkctl/releases/download/v1.0.33/cakeworkctl_1.0.33_Darwin_arm64.tar.gz"
      sha256 "3efcefaa58c9f94eaa33ebb8fcca00f53e1691db161aa3eae54d70a285006f7a"

      def install
        bin.install "cakework"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/usecakework/cakeworkctl/releases/download/v1.0.33/cakeworkctl_1.0.33_Linux_x86_64.tar.gz"
      sha256 "c526ce6d25e95439b66a3362909d96e0ffd7820488177995036ad7aa4f483a19"

      def install
        bin.install "cakework"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/usecakework/cakeworkctl/releases/download/v1.0.33/cakeworkctl_1.0.33_Linux_arm64.tar.gz"
      sha256 "c4497ccb55c4a68a66946a688a2de6ee88668ac4f8b04a4ea0a8d53fd3fe8da6"

      def install
        bin.install "cakework"
      end
    end
  end
end
