/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { JessieYoungApi } from "../../../..";
import * as core from "../../../../core";

export const MovieDoesNotExistError: core.serialization.Schema<
  serializers.MovieDoesNotExistError.Raw,
  JessieYoungApi.MovieId
> = core.serialization.lazy(async () => (await import("../../..")).MovieId);

export declare namespace MovieDoesNotExistError {
  type Raw = serializers.MovieId.Raw;
}
