/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "./environments";
import * as core from "./core";
import { Client as ClientClient } from "./api/resources/client/client/Client";
export declare namespace CakeworkApiClient {
    interface Options {
        environment?: environments.CakeworkApiEnvironment | string;
        xApiKey?: core.Supplier<string>;
        project: string;
    }
}
export declare class CakeworkApiClient {
    #private;
    private readonly options;
    constructor(options: CakeworkApiClient.Options);
    get client(): ClientClient;
}
