/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { Client as ImdbClient } from "./api/resources/imdb/client/Client";
export declare namespace JessieYoungApiClient {
    interface Options {
        environment: string;
    }
}
export declare class JessieYoungApiClient {
    #private;
    private readonly options;
    constructor(options: JessieYoungApiClient.Options);
    get imdb(): ImdbClient;
}
