/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const CakeworkApiEnvironment: {
    readonly Production: "https://cakework-frontend.fly.dev";
    readonly Local: "http://localhost:8080";
};
export declare type CakeworkApiEnvironment = typeof CakeworkApiEnvironment.Production | typeof CakeworkApiEnvironment.Local;
