/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CakeworkApi } from "../../../..";

export interface RunRequest {
  parameters?: CakeworkApi.Parameters;
  compute?: CakeworkApi.Compute;
}
