/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Status = "PENDING" | "IN_PROGRESS" | "SUCCEEDED" | "FAILED";

export const Status = {
  Pending: "PENDING",
  InProgress: "IN_PROGRESS",
  Succeeded: "SUCCEEDED",
  Failed: "FAILED",
} as const;
