/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class CakeworkApiTimeoutError extends Error {
  constructor() {
    super("Timeout");
    Object.setPrototypeOf(this, CakeworkApiTimeoutError.prototype);
  }
}
