/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { JessieYoungApi } from "../../../..";
import * as core from "../../../../core";
export declare const CreateMovieRequest: core.serialization.ObjectSchema<serializers.CreateMovieRequest.Raw, JessieYoungApi.CreateMovieRequest>;
export declare namespace CreateMovieRequest {
    interface Raw {
        title: string;
        rating: number;
    }
}
