/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { JessieYoungApi } from "../../../..";
import * as core from "../../../../core";
export declare const MovieId: core.serialization.Schema<serializers.MovieId.Raw, JessieYoungApi.MovieId>;
export declare namespace MovieId {
    type Raw = string;
}
