/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { CakeworkApi } from "../../../..";
export interface Movie {
    id: CakeworkApi.MovieId;
    title: string;
    /** The rating scale is one to five stars */
    rating: number;
}
