/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { JessieYoungApi } from "../../../..";

export class MovieDoesNotExistError extends Error {
  readonly body: JessieYoungApi.MovieId;

  constructor(body: JessieYoungApi.MovieId) {
    super();
    Object.setPrototypeOf(this, MovieDoesNotExistError.prototype);
    this.body = body;
  }
}
