/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import { Client as ClientClient } from "./api/resources/client/client/Client";

export declare namespace CakeworkApiClient {
  interface Options {
    environment?: environments.CakeworkApiEnvironment | string;
  }
}

export class CakeworkApiClient {
  constructor(private readonly options: CakeworkApiClient.Options) {}

  #client: ClientClient | undefined;

  public get client(): ClientClient {
    return (this.#client ??= new ClientClient(this.options));
  }
}
