/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const CakeworkApiEnvironment = {
  Production: "https://cakework-frontend.fly.dev",
  Local: "http://localhost:8080",
} as const;

export type CakeworkApiEnvironment =
  | typeof CakeworkApiEnvironment.Production
  | typeof CakeworkApiEnvironment.Local;
