/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare class CakeworkApiError extends Error {
    readonly statusCode?: number;
    readonly responseBody?: unknown;
    constructor({ message, statusCode, responseBody, }: {
        message?: string;
        statusCode?: number;
        responseBody?: string;
    });
}
