/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { JessieYoungApi } from "../../../..";
export declare namespace Client {
    interface Options {
        environment: string;
    }
}
export declare class Client {
    private readonly options;
    constructor(options: Client.Options);
    /**
     * Add a movie to the database
     */
    createMovie(request: JessieYoungApi.CreateMovieRequest): Promise<JessieYoungApi.MovieId>;
    /**
     * @throws {JessieYoungApi.MovieDoesNotExistError}
     */
    getMovie(movieId: JessieYoungApi.MovieId): Promise<JessieYoungApi.Movie>;
}
