/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { CakeworkApi } from "../../../..";
export declare namespace Client {
    interface Options {
        environment?: environments.CakeworkApiEnvironment | string;
        xApiKey?: core.Supplier<string>;
        name: string;
    }
}
export declare class Client {
    private readonly options;
    constructor(options: Client.Options);
    /**
     * Get the status of a run
     * @throws {CakeworkApi.RunDoesNotExistError}
     */
    getRunStatus(runId: CakeworkApi.RunId): Promise<CakeworkApi.Status>;
    /**
     * Get the result of a run
     * @throws {CakeworkApi.RunDoesNotExistError}
     */
    getRunResult(runId: CakeworkApi.RunId): Promise<CakeworkApi.RunResult | undefined>;
    /**
     * Run a task
     * @throws {CakeworkApi.RunDoesNotExistError}
     */
    run(request: CakeworkApi.RunRequest): Promise<CakeworkApi.RunId>;
}
