/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { CakeworkApi } from "../../../..";
import * as core from "../../../../core";
export declare const MovieDoesNotExistError: core.serialization.Schema<serializers.MovieDoesNotExistError.Raw, CakeworkApi.MovieId>;
export declare namespace MovieDoesNotExistError {
    type Raw = serializers.MovieId.Raw;
}
