/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { JessieYoungApi } from "../../../..";
export declare class MovieDoesNotExistError extends Error {
    readonly body: JessieYoungApi.MovieId;
    constructor(body: JessieYoungApi.MovieId);
}
