/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { CakeworkApi } from "../../../..";
export declare class MovieDoesNotExistError extends Error {
    readonly body: CakeworkApi.MovieId;
    constructor(body: CakeworkApi.MovieId);
}
